### ISSUE TITLE
Implement home

### ISSUE THREAD

**Issue by pbellon** [Skoli-Code/DerangeonsLaChambre#7]
![image](https://cloud.githubusercontent.com/assets/1018824/20705728/678e79dc-b624-11e6-9f8c-db887b5b11e1.png)

**Comment by gothborg** [comment]
Suggestion de contenu texte pour la cover @pbellon :

Titre 1 : DÉRANGEONS LA CHAMBRE
Titre 2 : " Assemblée Nationale : et si on changeait les règles du jeu ? 
Titre 3 : Une simulation électorale par Skoli et Raul Magni-Berton

**Comment by pbellon** [comment]
Au passage je précise que les indications de navigation (clavier + swipe) ne sont plus d'actualité sur la home (elle apparaîtront une fois que nous commençons à voir l'étude).
